
hydra:
  run:
    dir: outputs/vae/${now:%Y-%m-%d}/${now:%H-%M-%S}
model_dir: models

dataset_path: /DATAPATH

verbose: True

labels: [1080Lines, 1400Ripples, Air_Compressor, Blip,
         Chirp, Extremely_Loud, Helix, Koi_Fish,
         Light_Modulation, Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
         None_of_the_Above, Paired_Doves, Power_Line, Repeating_Blips,
         Scattered_Light, Scratchy, Tomte, Violin_Mode,
         Wandering_Line, Whistle]

random_state: 123
in_channels: 4
train_size: 0.8
z_dim: 512
lr: 5e-4
num_epoch: 1000
batch_size: 96
num_train_step: 100
save_itvl: 50
eval_itvl: 5


gpu:
  train: 0
  eval: 1

# for evaluation
trained_model_file: vae_e100.pt

wandb:
  is_output: true
  project: gw-deep
  group: vae
  name: vae
  cwd: current_work_directory
